import React from 'react'
import DocumentTitle from 'react-document-title'
import styles from './styles.css'

export default class Travel extends React.Component {
	render() {
		return (
			<DocumentTitle title='Travel Info'>
				<article className='content'>
					<h2 className='title'>Travel Info</h2>
					<p>We know a lot of our guests will be visiting the Tri-Cities for the very first time, so we compiled some information to help people get here, know where to stay while here, and be aware of the attractions the Tri-Cities have to offer. If you have any questions, feel free to reach out to the grooms for help.</p>
					<ul className={styles.tableOfContents}>
						<li><a href='#hotel' title='Jump to Hotel information'>Hotels &amp; Lodgings</a></li>
						<li><a href='#flights' title='Jump to Flight information'>Flights</a></li>
						<li><a href='#tri-cities' title='Jump to information about the Tri-Cities'>About the Tri-Cities</a></li>
						<li><a href='#mansion' title='Jump to information about the Moore Mansion'>About the Moore Mansion</a></li>
					</ul>
					<div className={styles.clear} />
					<h3 className='subsection' id='hotel'>Hotels &amp; Lodgings</h3>
					<p>We have a hotel block booked for the wedding at the <a href='https://goo.gl/maps/kERXqHHzX8y' title='Best Western on Google Maps'>Best Western in Pasco</a>, conveniently located within minutes of the Pasco Airport (PSC) and the Moore Mansion. Best Western has graciously agreed to extend the group rate for as long before and after the wedding as you care to stay, so feel free to spend some time exploring the Tri-Cities. The block includes both rooms with a single king bed ($133/night) and rooms with two queen beds ($138/night) and both can be turned into suites for $10/night more. To book with the hotel block, either use <a href='http://book.bestwestern.com/bestwestern/groupSearch.do?groupId=3D2NZ7F0' title='Book on the Best Western website'>their website</a> or call 1 (866) 313-7599 and tell them you&rsquo;re with the Carver wedding. If you book online, make sure to check the dates&mdash;the website defaults to only a single night. If you plan on staying for more than the nights of the 7th and 8th we recommend you call the hotel, instead of booking online; the website will give you grief about it, as those are the days we have the block for.</p>
					<p>Best Western will provide a shuttle from the airport to the hotel, if that&rsquo;s something you wish to take advantage of. Check back in later for more information on how to set that up, or ask while booking. We will be making every effort to provide a shuttle from the Best Western to the wedding and reception, along with transportation back after the reception, so check back later for more information on that, as well.</p>
					<p>Beyond the Best Western, you may have some luck using sites like <a href='https://airbnb.com' title='Airbnb'>Airbnb</a> to find houses, rooms, and other alternative accomodations for rental. We would advise you to try and stay in the Pasco area, as opposed to Richland or Kennewick, to avoid being too far from the venue and the other guests.</p>
					<h3 className='subsection' id='flights'>Flights</h3>
					<p>When flying into the Tri-Cities, you have basically three options, depending on whether you wish to drive or not.</p>
					<ul>
						<li>Flying into the Pasco airport (PSC) is the easiest option, as a shuttle will bring you directly to the Best Western, and the airport will be just minutes away. If you are only going to be in town for a night or two, we highly recommend flying into PSC and using the provided shuttle services, rather than renting a car.</li>
						<li>Flying into the Seattle airport (SEA) may save you up to a couple hundred dollars on the flights, but it means you&rsquo;ll be responsible for getting yourself from Seattle to the Tri-Cities; this is about a 3 hour drive through the mountains, but it&rsquo;s not a hard drive, and is very scenic. If you are interested in sightseeing in the Seattle area and you are not averse to a bit of driving, flying into SEA is a great option. Note that there are multiple passes through the mountains when coming from Seattle; <a href='https://goo.gl/maps/9pVD1My3pd32' title='Directions from SEA to Best Western through the Snoqualmie pass'>the Snoqualmie pass</a> is going to be the quickest and is the most-frequently used, but there&rsquo;s also <a href='https://goo.gl/maps/95r7HA7vUS52' title='Directions from SEA to Best Western through White Pass'>White Pass</a>, which takes a bit longer but is incredibly scenic.</li>
						<li>Flying into the Portland airport (PDX), like the Seattle airport, may save you up to a couple hundred dollars on flights, but it is also about a 3 hour drive to the Tri-Cities. If you&rsquo;re interested in visiting Portland, or if you want to save money on the flights and will need a rental car anyways, Portland is another great option. The drive from <a href='https://goo.gl/maps/7DgGKxxYsnx' title='Directions from PDX to Best Western'>Portland to the Tri-Cities</a> goes along the Columbia River, and is a little easier than the route from Seattle, as much less of it goes through mountains.</li>
					</ul>
					<p>All three airports have rental car locations in the airport, if you want to rent a car for your visit. SEA has more information on the <a href='https://www.portseattle.org/Sea-Tac/Parking-and-Transportation/Ground-Transportation/Pages/Rental-Cars.aspx' title='Rental Car info for Seattle'>Port of Seattle website</a>. PDX has more information on the <a href='https://www2.portofportland.com/PDX/GroundTransportation' title='Rental Car info for Portland'>Port of Portland website</a>. PSC has more information on the <a href='http://www.flytricities.com/fly/ground-transportation' title='Rental Car info for Pasco'>Tri-Cities Airport website</a>.</p>
					<p>When booking your flights, we highly recommend you use <a href='https://google.com/flights' title='Google Flights'>Google Flights</a>, a tool that lets you search flights from all the major airlines, and has a bunch of advanced options that help you find the best price or most convenient flight, whichever is most important to you. To help people make the most of Google Flights, we&rsquo;ve put together <a href='https://youtu.be/hCPnMzYKSoM' title='Screencast tutorial of using Google Flights'>a quick screencast tutorial</a> showing how to use it.</p>
					<h3 className='subsection' id='tri-cities'>About the Tri-Cities</h3>
					<p>The Tri-Cities is technically in a desert, but is located right at the confluence of the Snake, Yakima, &amp; Columbia rivers, so it&rsquo;s probably not like the deserts you&rsquo;re thinking of&mdash;it has plenty of grass, for example. It consists of the cities of Richland, Kennewick, and Pasco; Paddy and Ethan live in Richland, and the wedding will be happening in Pasco. We expect it to be hot&mdash;around 100 degrees!&mdash;so dress accordingly, though there will be plenty of shade, and the venue is right next to the Columbia River, which cools things down significantly. Also, there isn&rsquo;t much humidity, so the heat tends to be more bearable that a day with comparable temperatures in, for example, New York. As a general rule of thumb, we don&rsquo;t expect much rain, but any rain we do get in the summer tends to be a pretty quick shower. We also tend to have pretty clear skies, so sunblock is advised.</p>
					<p>The Tri-Cities traces its history (for the most part) back to the creation of the Manhattan project; the Hanford B-Reactor was the first reactor to produce weapons-grade plutonium and its plutonium was used in the tests of the atomic bomb. The cities grew around the scientists and military personnel working on the project, and were only expected to last until the bomb was completed. However, after their work was finished, many of the people involved chose to stay in the Tri-Cities. You&rsquo;ll notice many of the roads here are named for engineers. The Hanford B-Reactor was recently designated as a national park, and the ongoing cleanup efforts for the project drive a large part of the economy here. Despite being three cities, the Tri-Cities often has a small town feel to it, and people travel pretty frequently between the three cities, largely treating it as one. The Tri-Cities is also a notable center for scientific research; most famous is probably the LIGO research facility that aided in the detection of gravitational waves. Because of its desert location, the Tri-Cities is surrounded by wilderness in pretty much every direction, and driving thirty minutes outside of the cities will provide a beautiful stargazing opportunity with very little light polution. Thanks to some glacial deposits from the last Ice Age, the Tri-Cities has very fertile land and a perfect climate for grapes, so we have a booming wine industry here, and highly recommend visiting one of the many wineries in the area.</p>
					<h3 className='subsection' id='mansion'>About the Moore Mansion</h3>
					<p>Our ceremony will be taking place on the steps of the Moore Mansion, and the reception will follow on the lawn with the carriage house and mansion as a backdrop. Due to legal constraints, nobody will be allowed inside the Mansion itself, but there are buildings available for restrooms and there is a pavillion available in case of inclement weather. Though there is a floored gazebo that serves as the dancefloor, expect to be walking on grass for much of the day; choose footwear appropriately. The Mansion offers lots of shade, but do anticipate being out in the sun for the day. The Mansion is a popular wedding destination, and other couples wil be using it the week after us, so please help us keep it nice for them.</p>
					<p>The Mansion was constructed over a century ago by James A. Moore for his bride. After Moore&rsquo;s death, the Mansion ended up with an owner that tried to burn it down for insurance money. The Mansion then stood, damaged and uncared for, until the current owners purchased it just before it was scheduled to be demolished. They put in a lot of effort to restore the Mansion to its former glory, taking great pains to use as many of the original materials as possible, and using era-appropriate materials when necessary. Due to its historic restoration and its listing as a historic landmark, there is limited access inside the building, as its original design does not meet current building codes, and the owners wish to preserve its historic beauty. The proceeds from events hosted at the Mansion are used to further the restoration of the building. If you&rsquo;re interested in the Mansion or its history, please speak to Deb, our host, who will be around at the wedding; she&rsquo;s more than happy to share.</p>
				</article>
			</DocumentTitle>
		)
	}
}
